### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by hscspring** [OpenSourceHomeschooler/SlimCalcPy#1]
Hello, Nice to asking you here.

When i run `Working_Calculator.py` , there is an error :    
print myCalc.calc(value) 
SyntaxError: invalid syntax   

and i don't know why~

**Comment by huberf** [comment]
It appears to be a Python 3 compatibility issue. I'm working now to port it over.

**Comment by huberf** [comment]
I have now added support for Python 3 in a copied version of the file located in this folder. https://github.com/huberf/SlimCalcPy/tree/master/Python3Version

Unfortunately, I can't both support Python 2 and 3 at the same time, as the raw_input isn't compatible with Python 3, but required for Python 2.

Just so you know what was going wrong, Python 3 requires that one use `print` like a function, so one has to use it like `print("Hello World!")` instead of `print "Hello World!"`
